[project]
name = "vixtk"
version = "0.1.0"
description = "Tools for various tasks"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "elasticsearch<9", # Keep an eye on the version compatibility with Elasticsearch.
    "pandas>=2.3.3",
    "tqdm>=4.67.1",
    "orjson>=3.10.12"
]
